name: master-branch-ci

on:
  push:
    branches:
      - master

# https://www.cypress.io/blog/2019/11/20/drastically-simplify-your-testing-with-cypress-github-action/
jobs:
  test:
    name: Test
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: yarn
      env:
        CI: true
    - uses: cypress-io/github-action@v1
      with:
        start: yarn start
        config: pageLoadTimeout=100000,watchForFileChanges=false
        parallel: true
        browser: chrome
        headless: true
        group: 'simple-time-tracker'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: yarn && yarn build
